= Create a JAX-RS application using Bootable Jar - part one: bare metal
:summary: ONELINE EXPLANATION OF THE GUIDE
:includedir: ../_includes
include::{includedir}/_attributes.adoc[]
// you can override any attributes eg to lengthen the
// time to complete the guide
:prerequisites-time: 10

In this guide, you will learn how to run a simple JAX-RS application using Bootable Jar.

include::{includedir}/_prerequisites.adoc[]

include::_includes/_dependencies.adoc[]

== Maven Project

We will get inspired by link:https://github.com/wildfly-extras/wildfly-jar-maven-plugin/tree/main/examples/jaxrs[JAX-RS WildFly bootable jar example] in the official link:https://github.com/wildfly-extras/wildfly-jar-maven-plugin[wildfly-jar-maven-plugin] and make a few adjustments to make it a standalone project;

=== Pom File

Create an empty directory named `jaxrs` which will be the root of your maven project;

Add file `pom.xml` with the following content to the `jaxrs` directory:

{jaxrs-example-project-groupId}

[source,xml,subs="normal"]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>{jaxrs-example-project-groupId}</groupId>
    <artifactId>{jaxrs-example-project-artifactId}</artifactId>
    <version>{jaxrs-example-project-version}</version>

    <packaging>war</packaging>

    <name>WildFly Bootable JAR - JAX-RS Example</name>
    <description>An example of how to use JAX-RS resources</description>

    <properties>
        <version.bootable.jar>{version-bootable-jar}</version.bootable.jar>
        <version.wildfly>{version-wildfly-galleon-pack}</version.wildfly>
        <plugin.fork.embedded>true</plugin.fork.embedded>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>jakarta.platform</groupId>
                <artifactId>jakarta.jakartaee-api</artifactId>
                <version>{jakarta-jakartaee-api-version}</version>
                <scope>provided</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.wildfly.plugins</groupId>
                <artifactId>wildfly-jar-maven-plugin</artifactId>
                <version>${version.bootable.jar}</version>
                <configuration>
                    <feature-packs>
                        <feature-pack>
                            <location>org.wildfly:wildfly-galleon-pack:${version.wildfly}</location>
                        </feature-pack>
                    </feature-packs>
                    <layers>
                        <layer>jaxrs</layer>
                        <layer>management</layer>
                    </layers>
                    <excluded-layers>
                        <layer>deployment-scanner</layer>
                    </excluded-layers>
                    <plugin-options>
                        <jboss-fork-embedded>${plugin.fork.embedded}</jboss-fork-embedded>
                    </plugin-options>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
----

=== JAX-RS Service

In the same directory as the `pom.xml` file, create the following directory tree `src/main/java/org/wildfly/plugins/demo/jaxrs`, like e.g.:

[source,bash]
----
mkdir -p src/main/java/org/wildfly/plugins/demo/jaxrs
----

Then create the two following two files:

`src/main/java/org/wildfly/plugins/demo/jaxrs/RestApplication.java`:

[source,java]
----
package org.wildfly.plugins.demo.jaxrs;

import jakarta.ws.rs.ApplicationPath;
import jakarta.ws.rs.core.Application;

@ApplicationPath("/")
public class RestApplication extends Application {
}
----

`src/main/java/org/wildfly/plugins/demo/jaxrs/HelloWorldEndpoint.java`:

[source,java]
----
package org.wildfly.plugins.demo.jaxrs;


import jakarta.ws.rs.Path;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Produces;


@Path("/hello")
public class HelloWorldEndpoint {
    @GET
    @Produces("text/plain")
    public Response doGet() {
        return Response.ok("Hello from WildFly bootable jar!").build();
    }
}
----

=== Build the application

[source,bash]
----
mvn clean package
----

=== Run the application

[source,bash]
----
java -jar target/jaxrs-bootable.jar
...
10:32:13,949 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-7) WFLYUT0006: Undertow HTTP listener default listening on 127.0.0.1:8080
10:32:13,951 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0027: Starting deployment of "jaxrs.war" (runtime-name: "ROOT.war")
10:32:14,415 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 15) RESTEASY002225: Deploying jakarta.ws.rs.core.Application: class org.wildfly.plugins.demo.jaxrs.RestApplication
10:32:14,436 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 15) WFLYUT0021: Registered web context: '/' for server 'default-server'
10:32:14,438 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0010: Deployed "jaxrs.war" (runtime-name : "ROOT.war")
10:32:14,455 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
10:32:14,457 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
10:32:14,457 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0054: Admin console is not enabled
10:32:14,458 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Full 31.0.1.Final (WildFly Core 23.0.3.Final) started in 1013ms - Started 159 of 163 services (30 services are lazy, passive or on-demand) - Server configuration file in use: standalone.xml
----

As you can see the applications starts in ~ 1 second!

=== Check the application

You can hit this url link:http://127.0.0.1:8080/hello[http://127.0.0.1:8080/hello] in your browser, or you can use a utility like `curl`:

[source,bash]
----
curl http://127.0.0.1:8080/hello
Hello from WildFly bootable jar!
----

== Add a simple Test

We are using link:https://github.com/wildfly/wildfly-arquillian[WildFly Arquillian Adapter];

=== Pom file

Add the following properties to `pom.xml`:
[source,xml,subs="normal"]
----
<version.junit-jupiter-api>{version-junit-jupiter-api}</version.junit-jupiter-api>
<version.arquillian-junit5-container>{version-arquillian-junit5-container}</version.arquillian-junit5-container>
<version.org.wildfly.arquillian.wildfly-arquillian>{version-org-wildfly-arquillian-wildfly-arquillian}</version.org.wildfly.arquillian.wildfly-arquillian>
<version.resteasy-client>{version-resteasy-client}</version.resteasy-client>
----

Add the following dependencies to `pom.xml`:
[source,xml]
----
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-api</artifactId>
    <version>${version.junit-jupiter-api}</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.jboss.arquillian.junit5</groupId>
    <artifactId>arquillian-junit5-container</artifactId>
    <version>${version.arquillian-junit5-container}</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.wildfly.arquillian</groupId>
    <artifactId>wildfly-arquillian-container-bootable</artifactId>
    <version>${version.org.wildfly.arquillian.wildfly-arquillian}</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.jboss.resteasy</groupId>
    <artifactId>resteasy-client</artifactId>
    <version>${version.resteasy-client}</version>
    <scope>test</scope>
</dependency>
----

Add the following plugins to `pom.xml`:
[source,xml]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <configuration>
        <excludes>
            <exclude>.*BootableJarTestCase.*</exclude>
        </excludes>
    </configuration>
</plugin>
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-failsafe-plugin</artifactId>
    <executions>
        <execution>
            <id>jaxrs.surefire</id>
            <goals>
                <goal>integration-test</goal>
                <goal>verify</goal>
            </goals>
            <configuration>
                <includes>
                    <include>.*BootableJarTestCase.*</include>
                </includes>
                <failIfNoTests>true</failIfNoTests>
                <systemPropertyVariables>
                    <bootable.jar>${project.build.directory}/${project.artifactId}-bootable.jar</bootable.jar>
                    <arquillian.xml>arquillian.xml</arquillian.xml>
                </systemPropertyVariables>
                <redirectTestOutputToFile>false</redirectTestOutputToFile>
            </configuration>
        </execution>
    </executions>
</plugin>
----

=== Arquillian config file

Create file `src/test/resources/arquillian.xml` with the following content:
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<arquillian xmlns="http://jboss.org/schema/arquillian" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://jboss.org/schema/arquillian http://jboss.org/schema/arquillian/arquillian_1_0.xsd">
    <container qualifier="bootable-jar" default="true">
        <configuration>
            <property name="jarFile">${bootable.jar}</property>
            <property name="allowConnectingToRunningServer">false</property>
            <property name="managementAddress">127.0.0.1</property>
            <property name="managementPort">9990</property>
            <property name="waitForPorts">9990</property>
            <property name="waitForPortsTimeoutInSeconds">8</property>
        </configuration>
    </container>
</arquillian>
----

=== Test class

Add the test class `src/test/java/org/wildfly/plugins/demo/jaxrs/SimpleTestCase.java`:
[source,java]
----
package org.wildfly.plugins.demo.jaxrs;

import jakarta.ws.rs.client.Client;
import jakarta.ws.rs.client.ClientBuilder;
import jakarta.ws.rs.core.Response;
import org.jboss.arquillian.container.test.api.RunAsClient;
import org.jboss.arquillian.junit5.ArquillianExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import java.net.URI;

import static org.junit.jupiter.api.Assertions.assertEquals;

@RunAsClient
@ExtendWith(ArquillianExtension.class)
public class BootableJarTestCase {

	@Test
	public void testHelloEndpoint() {
		try (Client client = ClientBuilder.newClient()) {
			Response response = client
					.target(URI.create("http://127.0.0.1:8080/"))
					.path("/hello")
					.request()
					.get();

			assertEquals(200, response.getStatus());
			assertEquals("Hello from WildFly bootable jar!", response.readEntity(String.class));

		}
	}
}
----

=== Run the test

Now run the test which will start the bootable jar and make and http request to it:

[source,bash]
----
mvn clean install
...
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
...
10:45:16,538 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-7) WFLYUT0006: Undertow HTTP listener default listening on 127.0.0.1:8080
10:45:16,544 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0027: Starting deployment of "jaxrs.war" (runtime-name: "ROOT.war")
10:45:17,652 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 15) RESTEASY002225: Deploying jakarta.ws.rs.core.Application: class org.wildfly.plugins.demo.jaxrs.RestApplication
10:45:17,676 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 15) WFLYUT0021: Registered web context: '/' for server 'default-server'
10:45:17,680 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0010: Deployed "jaxrs.war" (runtime-name : "ROOT.war")
...
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
----

As you can see from the output:

* the bootable jar is started before the test is actually executed
* the link:http://127.0.0.1:8080/hello[http://127.0.0.1:8080/hello] endpoint, exposed by the bootable jar, is successfully invoked by the test

== What's next?

Next, we are going to deploy the same service on Kubernetes: link:simple-bootable-jar-part2[Create a JAX-RS application using Bootable Jar - part two: Kubernetes]

[[references]]
== References

* https://docs.wildfly.org/bootablejar/[WildFly Bootable JAR Documentation]
* https://www.wildfly.org/news/2020/10/19/bootable-jar-2.0-released/[WildFly Bootable JAR is final!]

< link:../get-started-microservices-on-kubernetes[Back to Getting Started with WildFly micro-services on Kubernetes]
